version: '3'
services:
  postgres_amx:
    image: postgres
    container_name: postgres_amx
    shm_size: 128mb
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /private/var/lib/postgres_amx:/var/lib/postgresql
    restart: unless-stopped
    networks:
      - db_net
      - db_net_admin
    env_file:
      - .env
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 5454:5454
    networks:
      - db_net_admin
networks:
  db_net:
    driver: bridge
  db_net_admin:
    driver: bridge